import assert from "node:assert"
import { describe, it } from "node:test"
import { generateGcode } from "./generate-gcode.ts"
import type { GcodeSettings } from "../types.ts"

describe("generateGcode", () => {
  const defaultGcodeSettings: GcodeSettings = {
    commands: {
      penUp: "M5",
      penDown: "M3 S1000",
      feedRate: "G1 F3000",
      pause: "G4 P0.5",
    },
    sheet: {
      targetX: 211,
      targetY: 297,
      padding: 20,
    },
  }

  it("should return valid GCODE for simple polylines", () => {
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    assert.ok(result.includes("; Generated by Line Weaver"))
    assert.ok(result.includes("M5"))
    assert.ok(result.includes("M3 S1000"))
    assert.ok(result.includes("G0 X0 Y0"))
  })

  it("should scale to fit DIN A4 sheet", () => {
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    const lines = result.split("\n")
    const moveLine = lines.find((l) => l.startsWith("G0 X") && l !== "G0 X0 Y0")

    assert.ok(moveLine)

    const match = moveLine.match(/G0 X([\d.]+) Y([\d.]+)/)
    assert.ok(match)

    const x = parseFloat(match[1])
    const y = parseFloat(match[2])

    assert.ok(x >= defaultGcodeSettings.sheet.padding)
    assert.ok(y >= defaultGcodeSettings.sheet.padding)
  })

  it("should optimize line order", () => {
    const polylines = [
      [
        { x: 80, y: 80 },
        { x: 90, y: 90 },
      ],
      [
        { x: 0, y: 0 },
        { x: 10, y: 10 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    const lines = result.split("\n")
    const rapidMoves = lines.filter((l) => l.startsWith("G0 X") && l !== "G0 X0 Y0")

    assert.strictEqual(rapidMoves.length, 2)
  })

  it("should use custom command settings", () => {
    const customSettings: GcodeSettings = {
      commands: {
        penUp: "M3 S0",
        penDown: "M3 S500",
        feedRate: "G1 F1000",
        pause: "G4 P2",
      },
      sheet: {
        targetX: 211,
        targetY: 297,
        padding: 20,
      },
    }
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: customSettings,
    })

    assert.ok(result.includes("M3 S0"))
    assert.ok(result.includes("M3 S500"))
    assert.ok(result.includes("G1 F1000"))
    assert.ok(result.includes("G4 P2"))
  })

  it("should handle empty polylines", () => {
    const result = generateGcode({
      polylines: [],
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    assert.ok(result.includes("; Generated by Line Weaver"))
    assert.ok(result.includes("G0 X0 Y0"))
  })

  it("should include pause after pen commands", () => {
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })
    const lines = result.split("\n")

    const penDownIndex = lines.findIndex((l) => l === "M3 S1000")
    assert.strictEqual(lines[penDownIndex + 1], "G4 P0.5")

    const penUpAfterDraw = lines.indexOf("M5", penDownIndex)
    assert.strictEqual(lines[penUpAfterDraw + 1], "G4 P0.5")
  })

  it("should handle different sheet sizes", () => {
    const customSettings: GcodeSettings = {
      commands: defaultGcodeSettings.commands,
      sheet: {
        targetX: 100,
        targetY: 100,
        padding: 10,
      },
    }
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: customSettings,
    })

    const lines = result.split("\n")
    const moveLine = lines.find((l) => l.startsWith("G0 X") && l !== "G0 X0 Y0")
    const match = moveLine?.match(/G0 X([\d.]+) Y([\d.]+)/)

    assert.ok(match)
    const x = parseFloat(match[1])
    const y = parseFloat(match[2])

    assert.ok(x >= 10)
    assert.ok(y >= 10)
    assert.ok(x <= 90)
    assert.ok(y <= 90)
  })

  it("should merge connected polylines before optimization", () => {
    const polylines = [
      [
        { x: 0, y: 0 },
        { x: 50, y: 50 },
      ],
      [
        { x: 50, y: 50 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    const lines = result.split("\n")
    const rapidMoves = lines.filter((l) => l.startsWith("G0 X") && l !== "G0 X0 Y0")

    assert.strictEqual(rapidMoves.length, 1)
  })

  it("should produce fewer pen lifts for connectable polylines", () => {
    const connectablePolylines = [
      [
        { x: 0, y: 0 },
        { x: 25, y: 25 },
      ],
      [
        { x: 25, y: 25 },
        { x: 50, y: 50 },
      ],
      [
        { x: 50, y: 50 },
        { x: 75, y: 75 },
      ],
      [
        { x: 75, y: 75 },
        { x: 100, y: 100 },
      ],
    ]
    const result = generateGcode({
      polylines: connectablePolylines,
      dimensions: { width: 100, height: 100 },
      gcodeSettings: defaultGcodeSettings,
    })

    const penUpCount = (result.match(/M5/g) || []).length

    assert.strictEqual(penUpCount, 3)
  })
})
