import type { GcodeCommandSettings, Point, Polyline } from "./types.ts"

type ConvertToGcodeCommandsInput = {
  polylines: Polyline[]
  commands: GcodeCommandSettings
}

export const convertToGcodeCommands = (params: ConvertToGcodeCommandsInput): string => {
  const { polylines, commands } = params

  const lines: string[] = []

  lines.push(...generateHeader(commands))
  lines.push(...generatePolylineCommands(polylines, commands))
  lines.push(...generateFooter())

  return lines.join("\n")
}

const generateHeader = (commands: GcodeCommandSettings): string[] => [
  "; Generated by Line Weaver",
  commands.penUp,
  commands.pause,
  commands.penDown,
  commands.pause,
  commands.penUp,
  commands.pause,
  commands.feedRate,
]

const generatePolylineCommands = (
  polylines: Polyline[],
  commands: GcodeCommandSettings
): string[] => {
  const lines: string[] = []

  for (const polyline of polylines) {
    if (polyline.length < 2) continue

    lines.push(...generateSinglePolyline(polyline, commands))
  }

  return lines
}

const generateSinglePolyline = (polyline: Polyline, commands: GcodeCommandSettings): string[] => {
  const lines: string[] = []
  const startPoint = polyline[0]

  lines.push(formatRapidMove(startPoint))
  lines.push(commands.penDown)
  lines.push(commands.pause)

  for (let i = 1; i < polyline.length; i++) {
    lines.push(formatLinearMove(polyline[i]))
  }

  lines.push(commands.penUp)
  lines.push(commands.pause)

  return lines
}

const generateFooter = (): string[] => ["G0 X0 Y0"]

const formatRapidMove = (point: Point): string =>
  `G0 X${formatCoord(point.x)} Y${formatCoord(point.y)}`

const formatLinearMove = (point: Point): string =>
  `G1 X${formatCoord(point.x)} Y${formatCoord(point.y)}`

const formatCoord = (value: number): string => {
  const rounded = Math.round(value * 100) / 100
  return Number.isInteger(rounded) ? rounded.toString() : rounded.toFixed(2)
}
