import assert from "node:assert"
import { describe, it } from "node:test"
import { convertToGcodeCommands } from "./convert-to-gcode-commands.ts"

describe("convertToGcodeCommands", () => {
  const defaultCommands = {
    penUp: "M5",
    penDown: "M3 S1000",
    feedRate: "G1 F3000",
    pause: "G4 P0.5",
  }

  it("should include header with pen up, pause, and feed rate", () => {
    const result = convertToGcodeCommands({
      polylines: [],
      commands: defaultCommands,
    })

    const lines = result.split("\n")

    assert.ok(lines.includes("; Generated by Line Weaver"))
    assert.ok(lines.includes("M5"))
    assert.ok(lines.includes("G4 P0.5"))
    assert.ok(lines.includes("G1 F3000"))
  })

  it("should generate rapid move to first point", () => {
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })

    assert.ok(result.includes("G0 X10 Y20"))
  })

  it("should include pen down and pause before drawing", () => {
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })
    const lines = result.split("\n")

    const rapidMoveIndex = lines.findIndex((l) => l === "G0 X10 Y20")
    const penDownIndex = lines.findIndex((l) => l === "M3 S1000")
    const pauseAfterPenDown = lines.indexOf("G4 P0.5", penDownIndex)

    assert.ok(penDownIndex > rapidMoveIndex)
    assert.strictEqual(pauseAfterPenDown, penDownIndex + 1)
  })

  it("should generate linear moves for polyline points", () => {
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }, { x: 50, y: 60 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })

    assert.ok(result.includes("G1 X30 Y40"))
    assert.ok(result.includes("G1 X50 Y60"))
  })

  it("should include pen up and pause after each polyline", () => {
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })
    const lines = result.split("\n")

    const linearMoveIndex = lines.findIndex((l) => l === "G1 X30 Y40")
    const penUpAfterDraw = lines.indexOf("M5", linearMoveIndex)
    const pauseAfterPenUp = lines.indexOf("G4 P0.5", penUpAfterDraw)

    assert.ok(penUpAfterDraw > linearMoveIndex)
    assert.strictEqual(pauseAfterPenUp, penUpAfterDraw + 1)
  })

  it("should return to origin at end", () => {
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })
    const lines = result.split("\n")

    assert.strictEqual(lines[lines.length - 1], "G0 X0 Y0")
  })

  it("should format coordinates with 2 decimal places", () => {
    const polylines = [[{ x: 10.123, y: 20.456 }, { x: 30.789, y: 40.999 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })

    assert.ok(result.includes("G0 X10.12 Y20.46"))
    assert.ok(result.includes("G1 X30.79 Y41"))
  })

  it("should use custom command settings", () => {
    const customCommands = {
      penUp: "M3 S0",
      penDown: "M3 S500",
      feedRate: "G1 F1000",
      pause: "G4 P1",
    }
    const polylines = [[{ x: 10, y: 20 }, { x: 30, y: 40 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: customCommands,
    })

    assert.ok(result.includes("M3 S0"))
    assert.ok(result.includes("M3 S500"))
    assert.ok(result.includes("G1 F1000"))
    assert.ok(result.includes("G4 P1"))
  })

  it("should handle empty polylines", () => {
    const polylines = [[], [{ x: 10, y: 20 }, { x: 30, y: 40 }], []]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })

    const linearMoveCount = (result.match(/G1 X/g) || []).length

    assert.strictEqual(linearMoveCount, 1)
  })

  it("should skip polylines with less than 2 points", () => {
    const polylines = [[{ x: 10, y: 20 }], [{ x: 30, y: 40 }, { x: 50, y: 60 }]]
    const result = convertToGcodeCommands({
      polylines,
      commands: defaultCommands,
    })

    assert.ok(!result.includes("G0 X10 Y20"))
    assert.ok(result.includes("G0 X30 Y40"))
  })
})

